### ISSUE TITLE
Create the Logo

### ISSUE THREAD

**Issue by KMConner** [yuyafukuchi/GestureGame#26]

**Comment by kojikojima0925** [comment]
![スクリーンショット 2020-06-25 17 54 08](https://user-images.githubusercontent.com/65969233/85689037-41864d80-b70d-11ea-92f1-8bcf4515d4fa.png)
![Cool-Text--357166701585142](https://user-images.githubusercontent.com/65969233/85689062-48ad5b80-b70d-11ea-8fe6-d430ba936a17.png)
![Cool-Text--357167878174903](https://user-images.githubusercontent.com/65969233/85689092-4e0aa600-b70d-11ea-9d02-9734538d8017.png)

**Comment by kojikojima0925** [comment]
![スクリーンショット 2020-06-25 18 10 13](https://user-images.githubusercontent.com/65969233/85691218-43e9a700-b70f-11ea-88fb-58423164bc76.png)

**Comment by kojikojima0925** [comment]
![PlayScreen_long](https://user-images.githubusercontent.com/65969233/86337807-8e799f00-bc8c-11ea-9909-2c38b295129d.png)
![PlayScreen_short](https://user-images.githubusercontent.com/65969233/86337829-92a5bc80-bc8c-11ea-8875-72a3a7ff21cd.png)

**Comment by kojikojima0925** [comment]
![スクリーンショット 2020-07-09 18 03 43](https://user-images.githubusercontent.com/65969233/87020587-0278f180-c20f-11ea-8305-eb91daf3ac70.png)
![スクリーンショット 2020-07-09 18 03 47](https://user-images.githubusercontent.com/65969233/87020595-060c7880-c20f-11ea-8bfa-f9f310491bfe.png)
![スクリーンショット 2020-07-09 18 03 52](https://user-images.githubusercontent.com/65969233/87020605-0a389600-c20f-11ea-821a-9c63e8e0d129.png)
